name: Publish Gem

on:
  release:
    types: [created]

jobs:
  publish-rubygems:
    runs-on: ubuntu-latest
    steps:
      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
